### ISSUE TITLE
CampaignsTriggerSend triggerProperties are string in package, but endpoint require object.

### ISSUE THREAD

**Issue by jpksoegaard** [braze-community/braze-php#37]
## Expected Behavior

I assumed that the triggerProperties on either CampaignsTriggerSendPostBody or CampaignsTriggerSendPostBodyRecipientsItem where json since the documentation says it is an object https://www.braze.com/docs/api/objects_filters/trigger_properties_object but the field(s) are in the code set as a string. 

## Actual Behavior

calling the endpoint with a string, any string result in the endpoint responding with : 
Bad Request - 'trigger_properties' must be an object

## Steps to Reproduce

Create a PostCampaignsTriggerSend with its CampaignsTriggerSendPostBody and setTriggerProperties on either body or CampaignsTriggerSendPostBodyRecipientsItem

## Reproducible Demo

n/a do to dev env.

## Environment

- Version: 1.3.1
- Platform:
- Browser: 
- OS:

**Comment by remarkablemark** [comment]
@jpksoegaard would you like to open a PR?

**Comment by remarkablemark** [comment]
Release:

- https://github.com/braze-community/braze-php/pull/39#issuecomment-1867437848
