### ISSUE TITLE
Symfony Serializer Incompatability

### ISSUE THREAD

**Issue by damiantw** [braze-community/braze-php#55]
Normalizers are incompatible with the contracts from the latest version of Symfony serializer. 

```
Fatal error: Declaration of Braze\Normalizer\JaneObjectNormalizer::denormalize($data, $class, $format = null, array $context = []) must be compatible with Symfony\Component\Serializer\Normalizer\DenormalizerInterface::denormalize(mixed $data, string $type, ?string $format = null, array $context = []): mixed in /Users/damian/Desktop/braze-php/lib/Normalizer/JaneObjectNormalizer.php on line 52
```

To reproduce, clone this repository, then run:

```bash
composer install && ./vendor/bin/pest
```

**Comment by remarkablemark** [comment]
@damiantw what version of PHP are you using?

**Comment by damiantw** [comment]
@remarkablemark 8.3

**Comment by remarkablemark** [comment]
@damiantw I was able to reproduce the error, I will work on a fix

**Comment by remarkablemark** [comment]
This seems to be related to https://github.com/janephp/janephp/issues/785

**Comment by remarkablemark** [comment]
@damiantw released:

- https://github.com/braze-community/braze-php/pull/58#issuecomment-1992718613
